export const backgroundTileMap = {
    frames: {
        "episode_one/arrow_green.tif": {
            frame: { x: 491, y: 421, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
        },
        "episode_one/arrow_green_down.tif": {
            frame: { x: 1577, y: 1, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
        },
        "episode_one/arrow_green_left.tif": {
            frame: { x: 1463, y: 273, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
        },
        "episode_one/arrow_green_up.tif": {
            frame: { x: 1565, y: 239, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
        },
        "episode_one/arrow_red.tif": {
            frame: { x: 1569, y: 341, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
        },
        "episode_one/arrow_red_down.tif": {
            frame: { x: 1577, y: 19, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
        },
        "episode_one/arrow_red_left.tif": {
            frame: { x: 1569, y: 359, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
        },
        "episode_one/arrow_red_up.tif": {
            frame: { x: 1577, y: 37, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
        },
        "episode_one/grass.tif": {
            frame: { x: 1569, y: 377, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
        },
        "episode_one/psp/tile_tree.tif": {
            frame: { x: 907, y: 291, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_balloons.tif": {
            frame: { x: 1255, y: 233, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_bat_sign.tif": {
            frame: { x: 1353, y: 199, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_blank.tif": {
            frame: { x: 393, y: 455, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_boulder.tif": {
            frame: { x: 809, y: 359, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_boulder02.tif": {
            frame: { x: 907, y: 325, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_castle.tif": {
            frame: { x: 941, y: 291, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_flowers.tif": {
            frame: { x: 1289, y: 233, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_gob_sign_down.tif": {
            frame: { x: 1387, y: 199, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_grass.tif": {
            frame: { x: 907, y: 291, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_mountain01.tif": {
            frame: { x: 427, y: 455, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_mountain02.tif": {
            frame: { x: 843, y: 359, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_mountain03.tif": {
            frame: { x: 941, y: 325, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_mountain04.tif": {
            frame: { x: 975, y: 291, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_sign_rox.tif": {
            frame: { x: 1323, y: 233, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_tree.tif": {
            frame: { x: 877, y: 359, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_tree02.tif": {
            frame: { x: 975, y: 325, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_turret_bottom_left.tif": {
            frame: { x: 1009, y: 291, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_turret_bottom_right.tif": {
            frame: { x: 1357, y: 233, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_turret_middle_left.tif": {
            frame: { x: 911, y: 359, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_turret_middle_right.tif": {
            frame: { x: 1009, y: 325, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_turret_top_left.tif": {
            frame: { x: 1043, y: 291, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_turret_top_right.tif": {
            frame: { x: 945, y: 359, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "episode_one/tile_wall.tif": {
            frame: { x: 1043, y: 325, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/_tileSet.tif": {
            frame: { x: 1, y: 291, w: 512, h: 128 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 512, h: 128 },
            sourceSize: { w: 512, h: 128 },
        },
        "level_two/cloudCastle/_tileSet.tif": {
            frame: { x: 1157, y: 1, w: 320, h: 128 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 320, h: 128 },
            sourceSize: { w: 320, h: 128 },
        },
        "level_two/cloudCastle/tile_cloud01.tif": {
            frame: { x: 1077, y: 291, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tile_cloud02.tif": {
            frame: { x: 979, y: 359, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tile_cloud03.tif": {
            frame: { x: 1077, y: 325, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tile_cloud04.tif": {
            frame: { x: 1111, y: 291, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tile_cloud05.tif": {
            frame: { x: 1013, y: 359, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tile_cloud06.tif": {
            frame: { x: 1111, y: 325, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tile_cloud07.tif": {
            frame: { x: 1047, y: 359, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tile_cloud08.tif": {
            frame: { x: 1081, y: 359, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tile_cloud09.tif": {
            frame: { x: 1421, y: 199, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tile_sky.tif": {
            frame: { x: 1391, y: 233, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tile_sky02.tif": {
            frame: { x: 461, y: 455, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_br_h01.tif": {
            frame: { x: 1115, y: 359, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_br_h02.tif": {
            frame: { x: 1425, y: 233, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_br_h03.tif": {
            frame: { x: 515, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_br_v01.tif": {
            frame: { x: 549, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_br_v02.tif": {
            frame: { x: 583, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_br_v03.tif": {
            frame: { x: 617, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_wl01.tif": {
            frame: { x: 651, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_wl02.tif": {
            frame: { x: 685, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_wl03.tif": {
            frame: { x: 719, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_wl04.tif": {
            frame: { x: 753, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_wl05.tif": {
            frame: { x: 787, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_wl06.tif": {
            frame: { x: 821, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/cloudCastle/tl_wl07.tif": {
            frame: { x: 855, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/tile_sign_blackFortress.tif": {
            frame: { x: 1, y: 421, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_blackOutpost.tif": {
            frame: { x: 515, y: 291, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_cavernsOfDarkness.tif": {
            frame: { x: 1157, y: 131, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_cavesOfDoom.tif": {
            frame: { x: 1479, y: 1, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_cavesOfFire.tif": {
            frame: { x: 1, y: 455, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_cavesOfSmoke.tif": {
            frame: { x: 99, y: 421, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_deadWoods.tif": {
            frame: { x: 515, y: 325, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_eastJungle.tif": {
            frame: { x: 613, y: 291, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_eastWoods.tif": {
            frame: { x: 1157, y: 165, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_goldenPalace.tif": {
            frame: { x: 1255, y: 131, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_innerSanctum.tif": {
            frame: { x: 1479, y: 35, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_uccaCopse.tif": {
            frame: { x: 99, y: 455, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_westJungle.tif": {
            frame: { x: 197, y: 421, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_wizardsGarden.tif": {
            frame: { x: 515, y: 359, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_wizardsStoreroom.tif": {
            frame: { x: 613, y: 325, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/tile_sign_woodsOfDecay.tif": {
            frame: { x: 711, y: 291, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs/ts_bf1.tif": {
            frame: { x: 889, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_bf2.tif": {
            frame: { x: 923, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_bf3.tif": {
            frame: { x: 957, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_bo1.tif": {
            frame: { x: 991, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_bo2.tif": {
            frame: { x: 1025, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_bo3.tif": {
            frame: { x: 1059, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_cad1.tif": {
            frame: { x: 1093, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_cad2.tif": {
            frame: { x: 1479, y: 103, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_cad3.tif": {
            frame: { x: 1513, y: 103, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_cod1.tif": {
            frame: { x: 1547, y: 103, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_cod2.tif": {
            frame: { x: 1157, y: 267, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_cof1.tif": {
            frame: { x: 1191, y: 267, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_cof2.tif": {
            frame: { x: 1225, y: 267, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_cos1.tif": {
            frame: { x: 1259, y: 267, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_cos2.tif": {
            frame: { x: 1293, y: 267, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_cos3.tif": {
            frame: { x: 1327, y: 267, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_dw1.tif": {
            frame: { x: 1361, y: 267, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_dw2.tif": {
            frame: { x: 1395, y: 267, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_ej1.tif": {
            frame: { x: 1429, y: 267, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_ej2.tif": {
            frame: { x: 1127, y: 393, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_ew1.tif": {
            frame: { x: 1145, y: 301, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_ew2.tif": {
            frame: { x: 1179, y: 301, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_gp1.tif": {
            frame: { x: 1213, y: 301, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_gp2.tif": {
            frame: { x: 1247, y: 301, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_gp3.tif": {
            frame: { x: 1281, y: 301, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_is1.tif": {
            frame: { x: 1315, y: 301, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_is2.tif": {
            frame: { x: 1349, y: 301, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_is3.tif": {
            frame: { x: 1383, y: 301, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_uc1.tif": {
            frame: { x: 1417, y: 301, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_uc2.tif": {
            frame: { x: 1451, y: 301, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_wg1.tif": {
            frame: { x: 1149, y: 335, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_wg2.tif": {
            frame: { x: 1183, y: 335, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_wg3.tif": {
            frame: { x: 1217, y: 335, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_wj1.tif": {
            frame: { x: 1251, y: 335, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_wj2.tif": {
            frame: { x: 1285, y: 335, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_wod1.tif": {
            frame: { x: 1319, y: 335, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_wod2.tif": {
            frame: { x: 1353, y: 335, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_wod3.tif": {
            frame: { x: 1387, y: 335, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_ws1.tif": {
            frame: { x: 1421, y: 335, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_ws2.tif": {
            frame: { x: 1455, y: 335, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs/ts_ws3.tif": {
            frame: { x: 1161, y: 369, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/tile_sign_blackFortress.tif": {
            frame: { x: 1157, y: 199, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_blackOutpost.tif": {
            frame: { x: 1255, y: 165, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_cavernsOfDarkness.tif": {
            frame: { x: 1353, y: 131, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_cavesOfDoom.tif": {
            frame: { x: 1479, y: 69, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_cavesOfFire.tif": {
            frame: { x: 197, y: 455, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_cavesOfSmoke.tif": {
            frame: { x: 295, y: 421, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_deadWoods.tif": {
            frame: { x: 613, y: 359, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_eastJungle.tif": {
            frame: { x: 711, y: 325, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_eastWoods.tif": {
            frame: { x: 809, y: 291, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_goldenPalace.tif": {
            frame: { x: 1157, y: 233, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_innerSanctum.tif": {
            frame: { x: 1255, y: 199, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_uccaCopse.tif": {
            frame: { x: 1353, y: 165, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_westJungle.tif": {
            frame: { x: 295, y: 455, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_wizardsGarden.tif": {
            frame: { x: 393, y: 421, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_wizardsStoreroom.tif": {
            frame: { x: 711, y: 359, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/tile_sign_woodsOfDecay.tif": {
            frame: { x: 809, y: 325, w: 96, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 96, h: 32 },
            sourceSize: { w: 96, h: 32 },
        },
        "level_two/signs_blck/ts_bf1.tif": {
            frame: { x: 1195, y: 369, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_bf2.tif": {
            frame: { x: 1229, y: 369, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_bf3.tif": {
            frame: { x: 1263, y: 369, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_bo1.tif": {
            frame: { x: 1297, y: 369, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_bo2.tif": {
            frame: { x: 1331, y: 369, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_bo3.tif": {
            frame: { x: 1365, y: 369, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_cad1.tif": {
            frame: { x: 1399, y: 369, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_cad2.tif": {
            frame: { x: 1433, y: 369, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_cad3.tif": {
            frame: { x: 1161, y: 403, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_cod1.tif": {
            frame: { x: 1195, y: 403, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_cod2.tif": {
            frame: { x: 1229, y: 403, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_cof1.tif": {
            frame: { x: 1263, y: 403, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_cof2.tif": {
            frame: { x: 1297, y: 403, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_cos1.tif": {
            frame: { x: 1331, y: 403, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_cos2.tif": {
            frame: { x: 1365, y: 403, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_cos3.tif": {
            frame: { x: 1399, y: 403, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_dw1.tif": {
            frame: { x: 1433, y: 403, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_dw2.tif": {
            frame: { x: 1467, y: 369, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_ej1.tif": {
            frame: { x: 1467, y: 403, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_ej2.tif": {
            frame: { x: 1451, y: 137, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_ew1.tif": {
            frame: { x: 1485, y: 137, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_ew2.tif": {
            frame: { x: 1519, y: 137, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_gp1.tif": {
            frame: { x: 1553, y: 137, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_gp2.tif": {
            frame: { x: 1455, y: 171, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_gp3.tif": {
            frame: { x: 1489, y: 171, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_is1.tif": {
            frame: { x: 1523, y: 171, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_is2.tif": {
            frame: { x: 1557, y: 171, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_is3.tif": {
            frame: { x: 1459, y: 205, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_uc1.tif": {
            frame: { x: 1493, y: 205, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_uc2.tif": {
            frame: { x: 1527, y: 205, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_wg1.tif": {
            frame: { x: 1561, y: 205, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_wg2.tif": {
            frame: { x: 1463, y: 239, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_wg3.tif": {
            frame: { x: 1497, y: 239, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_wj1.tif": {
            frame: { x: 1531, y: 239, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_wj2.tif": {
            frame: { x: 1485, y: 273, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_wod1.tif": {
            frame: { x: 1519, y: 273, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_wod2.tif": {
            frame: { x: 1553, y: 273, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_wod3.tif": {
            frame: { x: 1489, y: 307, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_ws1.tif": {
            frame: { x: 1523, y: 307, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_ws2.tif": {
            frame: { x: 1557, y: 307, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/signs_blck/ts_ws3.tif": {
            frame: { x: 1501, y: 341, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_basic.tif": {
            frame: { x: 1501, y: 375, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_blackearth.tif": {
            frame: { x: 1535, y: 341, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_blackendearth.tif": {
            frame: { x: 1535, y: 375, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_blacktile.tif": {
            frame: { x: 1501, y: 409, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_grass01.tif": {
            frame: { x: 907, y: 291, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_grass02.tif": {
            frame: { x: 1535, y: 409, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_grass03.tif": {
            frame: { x: 509, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_grass04.tif": {
            frame: { x: 543, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_grass05.tif": {
            frame: { x: 577, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_grass06.tif": {
            frame: { x: 611, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_grass07.tif": {
            frame: { x: 645, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_grass08.tif": {
            frame: { x: 679, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_grass09.tif": {
            frame: { x: 713, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_orcwall_centre.tif": {
            frame: { x: 747, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_orcwall_left.tif": {
            frame: { x: 781, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_orcwall_right.tif": {
            frame: { x: 815, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_orcwall_tower_bottom.tif": {
            frame: { x: 849, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_orcwall_tower_middle.tif": {
            frame: { x: 883, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_orcwall_tower_middle_left.tif": {
            frame: { x: 917, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_orcwall_tower_middle_right.tif": {
            frame: { x: 951, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_orcwall_tower_top.tif": {
            frame: { x: 985, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_rock.tif": {
            frame: { x: 1019, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_rocks.tif": {
            frame: { x: 1053, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_shrub01.tif": {
            frame: { x: 1087, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_skeleton_hand.tif": {
            frame: { x: 1121, y: 427, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_stones.tif": {
            frame: { x: 1155, y: 437, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_tree01.tif": {
            frame: { x: 1189, y: 437, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tile_tree02.tif": {
            frame: { x: 1223, y: 437, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_blk01.tif": {
            frame: { x: 1257, y: 437, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_blk02.tif": {
            frame: { x: 1291, y: 437, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_blk03.tif": {
            frame: { x: 1325, y: 437, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_blk04.tif": {
            frame: { x: 1359, y: 437, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_blk05.tif": {
            frame: { x: 1393, y: 437, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_blk06.tif": {
            frame: { x: 1427, y: 437, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_co01.tif": {
            frame: { x: 1461, y: 437, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_co02.tif": {
            frame: { x: 1495, y: 443, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_co03.tif": {
            frame: { x: 1529, y: 443, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_co04.tif": {
            frame: { x: 1563, y: 443, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_co05.tif": {
            frame: { x: 495, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_co06.tif": {
            frame: { x: 529, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_co07.tif": {
            frame: { x: 563, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_dr01.tif": {
            frame: { x: 597, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_dr02.tif": {
            frame: { x: 631, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_gl01.tif": {
            frame: { x: 665, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_gl02.tif": {
            frame: { x: 699, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_gl03.tif": {
            frame: { x: 733, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_gl04.tif": {
            frame: { x: 767, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_gl05.tif": {
            frame: { x: 801, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_glfl01.tif": {
            frame: { x: 835, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_glfl02.tif": {
            frame: { x: 869, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_lv01.tif": {
            frame: { x: 903, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_lv02.tif": {
            frame: { x: 937, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_lv03.tif": {
            frame: { x: 971, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_lv04.tif": {
            frame: { x: 1005, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_lv05.tif": {
            frame: { x: 1039, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_lv06.tif": {
            frame: { x: 1073, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_lv07.tif": {
            frame: { x: 1107, y: 461, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_lv08.tif": {
            frame: { x: 1141, y: 471, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_lv09.tif": {
            frame: { x: 1175, y: 471, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_pth01.tif": {
            frame: { x: 1209, y: 471, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_rk01.tif": {
            frame: { x: 1243, y: 471, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_sc01.tif": {
            frame: { x: 1277, y: 471, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_spw01.tif": {
            frame: { x: 1311, y: 471, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_srk01.tif": {
            frame: { x: 1345, y: 471, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_srk02.tif": {
            frame: { x: 1359, y: 437, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_srk03.tif": {
            frame: { x: 1379, y: 471, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_tr01.tif": {
            frame: { x: 1413, y: 471, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
        "level_two/tl_tr02.tif": {
            frame: { x: 1447, y: 471, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
        },
    },
    animations: {
        "episode_one/tile_mountain": [
            "episode_one/tile_mountain01.tif",
            "episode_one/tile_mountain02.tif",
            "episode_one/tile_mountain03.tif",
            "episode_one/tile_mountain04.tif",
        ],
        "level_two/cloudCastle/tile_cloud": [
            "level_two/cloudCastle/tile_cloud01.tif",
            "level_two/cloudCastle/tile_cloud02.tif",
            "level_two/cloudCastle/tile_cloud03.tif",
            "level_two/cloudCastle/tile_cloud04.tif",
            "level_two/cloudCastle/tile_cloud05.tif",
            "level_two/cloudCastle/tile_cloud06.tif",
            "level_two/cloudCastle/tile_cloud07.tif",
            "level_two/cloudCastle/tile_cloud08.tif",
            "level_two/cloudCastle/tile_cloud09.tif",
        ],
        "level_two/cloudCastle/tl_br_h": [
            "level_two/cloudCastle/tl_br_h01.tif",
            "level_two/cloudCastle/tl_br_h02.tif",
            "level_two/cloudCastle/tl_br_h03.tif",
        ],
        "level_two/cloudCastle/tl_br_v": [
            "level_two/cloudCastle/tl_br_v01.tif",
            "level_two/cloudCastle/tl_br_v02.tif",
            "level_two/cloudCastle/tl_br_v03.tif",
        ],
        "level_two/cloudCastle/tl_wl": [
            "level_two/cloudCastle/tl_wl01.tif",
            "level_two/cloudCastle/tl_wl02.tif",
            "level_two/cloudCastle/tl_wl03.tif",
            "level_two/cloudCastle/tl_wl04.tif",
            "level_two/cloudCastle/tl_wl05.tif",
            "level_two/cloudCastle/tl_wl06.tif",
            "level_two/cloudCastle/tl_wl07.tif",
        ],
        "level_two/signs/ts_bf": [
            "level_two/signs/ts_bf1.tif",
            "level_two/signs/ts_bf2.tif",
            "level_two/signs/ts_bf3.tif",
        ],
        "level_two/signs/ts_bo": [
            "level_two/signs/ts_bo1.tif",
            "level_two/signs/ts_bo2.tif",
            "level_two/signs/ts_bo3.tif",
        ],
        "level_two/signs/ts_cad": [
            "level_two/signs/ts_cad1.tif",
            "level_two/signs/ts_cad2.tif",
            "level_two/signs/ts_cad3.tif",
        ],
        "level_two/signs/ts_cod": [
            "level_two/signs/ts_cod1.tif",
            "level_two/signs/ts_cod2.tif",
        ],
        "level_two/signs/ts_cof": [
            "level_two/signs/ts_cof1.tif",
            "level_two/signs/ts_cof2.tif",
        ],
        "level_two/signs/ts_cos": [
            "level_two/signs/ts_cos1.tif",
            "level_two/signs/ts_cos2.tif",
            "level_two/signs/ts_cos3.tif",
        ],
        "level_two/signs/ts_dw": [
            "level_two/signs/ts_dw1.tif",
            "level_two/signs/ts_dw2.tif",
        ],
        "level_two/signs/ts_ej": [
            "level_two/signs/ts_ej1.tif",
            "level_two/signs/ts_ej2.tif",
        ],
        "level_two/signs/ts_ew": [
            "level_two/signs/ts_ew1.tif",
            "level_two/signs/ts_ew2.tif",
        ],
        "level_two/signs/ts_gp": [
            "level_two/signs/ts_gp1.tif",
            "level_two/signs/ts_gp2.tif",
            "level_two/signs/ts_gp3.tif",
        ],
        "level_two/signs/ts_is": [
            "level_two/signs/ts_is1.tif",
            "level_two/signs/ts_is2.tif",
            "level_two/signs/ts_is3.tif",
        ],
        "level_two/signs/ts_uc": [
            "level_two/signs/ts_uc1.tif",
            "level_two/signs/ts_uc2.tif",
        ],
        "level_two/signs/ts_wg": [
            "level_two/signs/ts_wg1.tif",
            "level_two/signs/ts_wg2.tif",
            "level_two/signs/ts_wg3.tif",
        ],
        "level_two/signs/ts_wj": [
            "level_two/signs/ts_wj1.tif",
            "level_two/signs/ts_wj2.tif",
        ],
        "level_two/signs/ts_wod": [
            "level_two/signs/ts_wod1.tif",
            "level_two/signs/ts_wod2.tif",
            "level_two/signs/ts_wod3.tif",
        ],
        "level_two/signs/ts_ws": [
            "level_two/signs/ts_ws1.tif",
            "level_two/signs/ts_ws2.tif",
            "level_two/signs/ts_ws3.tif",
        ],
        "level_two/signs_blck/ts_bf": [
            "level_two/signs_blck/ts_bf1.tif",
            "level_two/signs_blck/ts_bf2.tif",
            "level_two/signs_blck/ts_bf3.tif",
        ],
        "level_two/signs_blck/ts_bo": [
            "level_two/signs_blck/ts_bo1.tif",
            "level_two/signs_blck/ts_bo2.tif",
            "level_two/signs_blck/ts_bo3.tif",
        ],
        "level_two/signs_blck/ts_cad": [
            "level_two/signs_blck/ts_cad1.tif",
            "level_two/signs_blck/ts_cad2.tif",
            "level_two/signs_blck/ts_cad3.tif",
        ],
        "level_two/signs_blck/ts_cod": [
            "level_two/signs_blck/ts_cod1.tif",
            "level_two/signs_blck/ts_cod2.tif",
        ],
        "level_two/signs_blck/ts_cof": [
            "level_two/signs_blck/ts_cof1.tif",
            "level_two/signs_blck/ts_cof2.tif",
        ],
        "level_two/signs_blck/ts_cos": [
            "level_two/signs_blck/ts_cos1.tif",
            "level_two/signs_blck/ts_cos2.tif",
            "level_two/signs_blck/ts_cos3.tif",
        ],
        "level_two/signs_blck/ts_dw": [
            "level_two/signs_blck/ts_dw1.tif",
            "level_two/signs_blck/ts_dw2.tif",
        ],
        "level_two/signs_blck/ts_ej": [
            "level_two/signs_blck/ts_ej1.tif",
            "level_two/signs_blck/ts_ej2.tif",
        ],
        "level_two/signs_blck/ts_ew": [
            "level_two/signs_blck/ts_ew1.tif",
            "level_two/signs_blck/ts_ew2.tif",
        ],
        "level_two/signs_blck/ts_gp": [
            "level_two/signs_blck/ts_gp1.tif",
            "level_two/signs_blck/ts_gp2.tif",
            "level_two/signs_blck/ts_gp3.tif",
        ],
        "level_two/signs_blck/ts_is": [
            "level_two/signs_blck/ts_is1.tif",
            "level_two/signs_blck/ts_is2.tif",
            "level_two/signs_blck/ts_is3.tif",
        ],
        "level_two/signs_blck/ts_uc": [
            "level_two/signs_blck/ts_uc1.tif",
            "level_two/signs_blck/ts_uc2.tif",
        ],
        "level_two/signs_blck/ts_wg": [
            "level_two/signs_blck/ts_wg1.tif",
            "level_two/signs_blck/ts_wg2.tif",
            "level_two/signs_blck/ts_wg3.tif",
        ],
        "level_two/signs_blck/ts_wj": [
            "level_two/signs_blck/ts_wj1.tif",
            "level_two/signs_blck/ts_wj2.tif",
        ],
        "level_two/signs_blck/ts_wod": [
            "level_two/signs_blck/ts_wod1.tif",
            "level_two/signs_blck/ts_wod2.tif",
            "level_two/signs_blck/ts_wod3.tif",
        ],
        "level_two/signs_blck/ts_ws": [
            "level_two/signs_blck/ts_ws1.tif",
            "level_two/signs_blck/ts_ws2.tif",
            "level_two/signs_blck/ts_ws3.tif",
        ],
        "level_two/tile_grass": [
            "level_two/tile_grass01.tif",
            "level_two/tile_grass02.tif",
            "level_two/tile_grass03.tif",
            "level_two/tile_grass04.tif",
            "level_two/tile_grass05.tif",
            "level_two/tile_grass06.tif",
            "level_two/tile_grass07.tif",
            "level_two/tile_grass08.tif",
            "level_two/tile_grass09.tif",
        ],
        "level_two/tile_tree": [
            "level_two/tile_tree01.tif",
            "level_two/tile_tree02.tif",
        ],
        "level_two/tl_blk": [
            "level_two/tl_blk01.tif",
            "level_two/tl_blk02.tif",
            "level_two/tl_blk03.tif",
            "level_two/tl_blk04.tif",
            "level_two/tl_blk05.tif",
            "level_two/tl_blk06.tif",
        ],
        "level_two/tl_co": [
            "level_two/tl_co01.tif",
            "level_two/tl_co02.tif",
            "level_two/tl_co03.tif",
            "level_two/tl_co04.tif",
            "level_two/tl_co05.tif",
            "level_two/tl_co06.tif",
            "level_two/tl_co07.tif",
        ],
        "level_two/tl_dr": ["level_two/tl_dr01.tif", "level_two/tl_dr02.tif"],
        "level_two/tl_gl": [
            "level_two/tl_gl01.tif",
            "level_two/tl_gl02.tif",
            "level_two/tl_gl03.tif",
            "level_two/tl_gl04.tif",
            "level_two/tl_gl05.tif",
        ],
        "level_two/tl_glfl": [
            "level_two/tl_glfl01.tif",
            "level_two/tl_glfl02.tif",
        ],
        "level_two/tl_lv": [
            "level_two/tl_lv01.tif",
            "level_two/tl_lv02.tif",
            "level_two/tl_lv03.tif",
            "level_two/tl_lv04.tif",
            "level_two/tl_lv05.tif",
            "level_two/tl_lv06.tif",
            "level_two/tl_lv07.tif",
            "level_two/tl_lv08.tif",
            "level_two/tl_lv09.tif",
        ],
        "level_two/tl_srk": [
            "level_two/tl_srk01.tif",
            "level_two/tl_srk02.tif",
            "level_two/tl_srk03.tif",
        ],
        "level_two/tl_tr": ["level_two/tl_tr01.tif", "level_two/tl_tr02.tif"],
    },
    meta: {
        app: "https://www.codeandweb.com/texturepacker",
        version: "1.0",
        image: "background.png",
        format: "RGBA8888",
        size: { w: 1596, h: 504 },
        scale: "1",
        smartupdate:
            "$TexturePacker:SmartUpdate:081ce06ead2259a14c88093afdc43e2e:f4be8153481616bab92093174cec3d5f:2ba65c328dea799e4d80739630892abf$",
    },
};
