export const uiTileMap = {
    frames: {
        "_test_eBlast.tif": {
            frame: { x: 2010, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "_test_monster.tif": {
            frame: { x: 2026, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "arrow.tif": {
            frame: { x: 2774, y: 48, w: 48, h: 51 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 48, h: 51 },
            sourceSize: { w: 48, h: 51 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "background.tif": {
            frame: { x: 81, y: 0, w: 64, h: 10 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 64, h: 10 },
            sourceSize: { w: 64, h: 10 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "background03.tif": {
            frame: { x: 145, y: 0, w: 64, h: 10 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 64, h: 10 },
            sourceSize: { w: 64, h: 10 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "backgroundAlpha01.tif": {
            frame: { x: 209, y: 0, w: 64, h: 10 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 64, h: 10 },
            sourceSize: { w: 64, h: 10 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "backgroundAlpha02.tif": {
            frame: { x: 273, y: 0, w: 64, h: 10 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 64, h: 10 },
            sourceSize: { w: 64, h: 10 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "backgroundAlpha03.tif": {
            frame: { x: 337, y: 0, w: 64, h: 10 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 64, h: 10 },
            sourceSize: { w: 64, h: 10 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "behe01.tif": {
            frame: { x: 2882, y: 48, w: 63, h: 63 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 63, h: 63 },
            sourceSize: { w: 63, h: 63 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "bl_transform.tif": {
            frame: { x: 2822, y: 48, w: 60, h: 60 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 60, h: 60 },
            sourceSize: { w: 60, h: 60 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "bw_mr_small.tif": {
            frame: { x: 465, y: 48, w: 623, h: 45 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 623, h: 45 },
            sourceSize: { w: 623, h: 45 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "bw_mr_small_mask.tif": {
            frame: { x: 1088, y: 48, w: 623, h: 45 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 623, h: 45 },
            sourceSize: { w: 623, h: 45 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "cancel_butt.tif": {
            frame: { x: 0, y: 20, w: 104, h: 24 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 104, h: 24 },
            sourceSize: { w: 104, h: 24 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "cBrsts.tif": {
            frame: { x: 2042, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wAchrg01.tif": {
            frame: { x: 2058, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wAchrg02.tif": {
            frame: { x: 2074, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wAchrg03.tif": {
            frame: { x: 2090, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wAchrg04.tif": {
            frame: { x: 2106, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wFlchrg01.tif": {
            frame: { x: 2122, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wFlchrg02.tif": {
            frame: { x: 2138, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wFlchrg03.tif": {
            frame: { x: 2154, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wFlchrg04.tif": {
            frame: { x: 2170, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wFochrg01.tif": {
            frame: { x: 2186, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wFochrg02.tif": {
            frame: { x: 2202, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wFochrg03.tif": {
            frame: { x: 2218, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wFochrg04.tif": {
            frame: { x: 2234, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wGchrg01.tif": {
            frame: { x: 2250, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wGchrg02.tif": {
            frame: { x: 2266, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wGchrg03.tif": {
            frame: { x: 2282, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wGchrg04.tif": {
            frame: { x: 2298, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wPchrg01.tif": {
            frame: { x: 2314, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wPchrg02.tif": {
            frame: { x: 2330, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wPchrg03.tif": {
            frame: { x: 2346, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wPchrg04.tif": {
            frame: { x: 2362, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wUchrg01.tif": {
            frame: { x: 2378, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wUchrg02.tif": {
            frame: { x: 2394, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wUchrg03.tif": {
            frame: { x: 2410, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wUchrg04.tif": {
            frame: { x: 2426, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wVchrg01.tif": {
            frame: { x: 2442, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wVchrg02.tif": {
            frame: { x: 2458, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wVchrg03.tif": {
            frame: { x: 2474, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "charge/wVchrg04.tif": {
            frame: { x: 2490, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "Copy of wbFlaetorlin.tif": {
            frame: { x: 1040, y: 20, w: 25, h: 25 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 25, h: 25 },
            sourceSize: { w: 25, h: 25 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "Copy of wbFoelin.tif": {
            frame: { x: 1065, y: 20, w: 25, h: 25 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 25, h: 25 },
            sourceSize: { w: 25, h: 25 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "crystal_blue.tif": {
            frame: { x: 2506, y: 0, w: 11, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 11, h: 16 },
            sourceSize: { w: 11, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "e_bar_bar.tif": {
            frame: { x: 0, y: 0, w: 1, h: 1 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 1, h: 1 },
            sourceSize: { w: 1, h: 1 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "e_bar_grey.tif": {
            frame: { x: 1656, y: 0, w: 100, h: 14 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 100, h: 14 },
            sourceSize: { w: 100, h: 14 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "energy_bw.tif": {
            frame: { x: 585, y: 0, w: 77, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 77, h: 13 },
            sourceSize: { w: 77, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "energy_grey.tif": {
            frame: { x: 662, y: 0, w: 77, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 77, h: 13 },
            sourceSize: { w: 77, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "gmg_bullets.tif": {
            frame: { x: 2517, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "grey.tif": {
            frame: { x: 2533, y: 0, w: 11, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 11, h: 16 },
            sourceSize: { w: 11, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "greyshade.tif": {
            frame: { x: 2544, y: 0, w: 11, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 11, h: 16 },
            sourceSize: { w: 11, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "health_bw.tif": {
            frame: { x: 739, y: 0, w: 68, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 68, h: 13 },
            sourceSize: { w: 68, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "health_grey.tif": {
            frame: { x: 807, y: 0, w: 68, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 68, h: 13 },
            sourceSize: { w: 68, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "help.tif": {
            frame: { x: 1230, y: 20, w: 28, h: 26 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 28, h: 26 },
            sourceSize: { w: 28, h: 26 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "help_on.tif": {
            frame: { x: 1258, y: 20, w: 28, h: 26 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 28, h: 26 },
            sourceSize: { w: 28, h: 26 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "loadGame_butt.tif": {
            frame: { x: 104, y: 20, w: 104, h: 24 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 104, h: 24 },
            sourceSize: { w: 104, h: 24 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "merlinLogo.tif": {
            frame: { x: 1369, y: 120, w: 278, h: 88 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 278, h: 88 },
            sourceSize: { w: 278, h: 88 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "metalLogo.tif": {
            frame: { x: 1711, y: 48, w: 408, h: 45 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 408, h: 45 },
            sourceSize: { w: 408, h: 45 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "miniBack.tif": {
            frame: { x: 233, y: 48, w: 67, h: 31 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 67, h: 31 },
            sourceSize: { w: 67, h: 31 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "miniClear.tif": {
            frame: { x: 5, y: 0, w: 4, h: 4 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 4, h: 4 },
            sourceSize: { w: 4, h: 4 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "miniCurr.tif": {
            frame: { x: 9, y: 0, w: 4, h: 4 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 4, h: 4 },
            sourceSize: { w: 4, h: 4 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "miniInfest.tif": {
            frame: { x: 13, y: 0, w: 4, h: 4 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 4, h: 4 },
            sourceSize: { w: 4, h: 4 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "miniSpecial.tif": {
            frame: { x: 17, y: 0, w: 4, h: 4 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 4, h: 4 },
            sourceSize: { w: 4, h: 4 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "moBlank.tif": {
            frame: { x: 3227, y: 20, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "moBoulderMonster.tif": {
            frame: { x: 3256, y: 20, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "moGoblin.tif": {
            frame: { x: 3285, y: 20, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "moOrc.tif": {
            frame: { x: 3314, y: 20, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "moQuadranid.tif": {
            frame: { x: 3343, y: 20, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "morph_bw.tif": {
            frame: { x: 875, y: 0, w: 73, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 73, h: 13 },
            sourceSize: { w: 73, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "morph_grey.tif": {
            frame: { x: 948, y: 0, w: 73, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 73, h: 13 },
            sourceSize: { w: 73, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "moSkeleton.tif": {
            frame: { x: 3372, y: 20, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "mr_shading.tif": {
            frame: { x: 448, y: 48, w: 1, h: 36 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 1, h: 36 },
            sourceSize: { w: 1, h: 36 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "ms_blank.tif": {
            frame: { x: 3517, y: 20, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "ms_goblin.tif": {
            frame: { x: 3546, y: 20, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "ms_skeleton.tif": {
            frame: { x: 0, y: 48, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "msBoulderMonster.tif": {
            frame: { x: 3401, y: 20, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "msGhost.tif": {
            frame: { x: 3430, y: 20, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "msOrc.tif": {
            frame: { x: 3459, y: 20, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "msQuadranid.tif": {
            frame: { x: 3488, y: 20, w: 29, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 29, h: 28 },
            sourceSize: { w: 29, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "newGame_butt.gif": {
            frame: { x: 208, y: 20, w: 104, h: 24 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 104, h: 24 },
            sourceSize: { w: 104, h: 24 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "newGame_butt.tif": {
            frame: { x: 312, y: 20, w: 104, h: 24 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 104, h: 24 },
            sourceSize: { w: 104, h: 24 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "newHand.tif": {
            frame: { x: 3450, y: 0, w: 23, h: 19 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 23, h: 19 },
            sourceSize: { w: 23, h: 19 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "newRock.tif": {
            frame: { x: 416, y: 48, w: 32, h: 33 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 33 },
            sourceSize: { w: 32, h: 33 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "newTree.tif": {
            frame: { x: 320, y: 48, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "ok_butt.tif": {
            frame: { x: 416, y: 20, w: 104, h: 24 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 104, h: 24 },
            sourceSize: { w: 104, h: 24 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "old/help.tif": {
            frame: { x: 449, y: 48, w: 16, h: 39 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 39 },
            sourceSize: { w: 16, h: 39 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "oldBoulder.tif": {
            frame: { x: 203, y: 48, w: 30, h: 30 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 30, h: 30 },
            sourceSize: { w: 30, h: 30 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "oldTree.tif": {
            frame: { x: 300, y: 48, w: 20, h: 31 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 20, h: 31 },
            sourceSize: { w: 20, h: 31 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "outline.tif": {
            frame: { x: 2119, y: 48, w: 623, h: 45 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 623, h: 45 },
            sourceSize: { w: 623, h: 45 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/'.gif": {
            frame: { x: 113, y: 48, w: 30, h: 29 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 30, h: 29 },
            sourceSize: { w: 30, h: 29 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/'.tif": {
            frame: { x: 143, y: 48, w: 30, h: 29 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 30, h: 29 },
            sourceSize: { w: 30, h: 29 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/'.tif": {
            frame: { x: 173, y: 48, w: 30, h: 29 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 30, h: 29 },
            sourceSize: { w: 30, h: 29 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/border.tif": {
            frame: { x: 1647, y: 120, w: 1, h: 100 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 1, h: 100 },
            sourceSize: { w: 1, h: 100 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/E.bmp": {
            frame: { x: 2945, y: 48, w: 67, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 67, h: 72 },
            sourceSize: { w: 67, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/E.tif": {
            frame: { x: 3012, y: 48, w: 67, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 67, h: 72 },
            sourceSize: { w: 67, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/G.tif": {
            frame: { x: 3079, y: 48, w: 72, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 72, h: 72 },
            sourceSize: { w: 72, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/I.tif": {
            frame: { x: 3151, y: 48, w: 30, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 30, h: 72 },
            sourceSize: { w: 30, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/keys_butt.tif": {
            frame: { x: 520, y: 20, w: 104, h: 24 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 104, h: 24 },
            sourceSize: { w: 104, h: 24 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/L.tif": {
            frame: { x: 3181, y: 48, w: 63, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 63, h: 72 },
            sourceSize: { w: 63, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/M.tif": {
            frame: { x: 3244, y: 48, w: 91, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 91, h: 72 },
            sourceSize: { w: 91, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/N.tif": {
            frame: { x: 3335, y: 48, w: 82, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 82, h: 72 },
            sourceSize: { w: 82, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/options_butt.tif": {
            frame: { x: 624, y: 20, w: 104, h: 24 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 104, h: 24 },
            sourceSize: { w: 104, h: 24 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/R.tif": {
            frame: { x: 3417, y: 48, w: 81, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 81, h: 72 },
            sourceSize: { w: 81, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/S.tif": {
            frame: { x: 3498, y: 48, w: 68, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 68, h: 72 },
            sourceSize: { w: 68, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/scrollerAlpha.tif": {
            frame: { x: 1286, y: 20, w: 619, h: 26 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 619, h: 26 },
            sourceSize: { w: 619, h: 26 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/start_butt.tif": {
            frame: { x: 728, y: 20, w: 104, h: 24 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 104, h: 24 },
            sourceSize: { w: 104, h: 24 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/start_butt_alpha.tif": {
            frame: { x: 832, y: 20, w: 104, h: 24 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 104, h: 24 },
            sourceSize: { w: 104, h: 24 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/256col/V.tif": {
            frame: { x: 0, y: 120, w: 87, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 87, h: 72 },
            sourceSize: { w: 87, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/background.gif": {
            frame: { x: 1, y: 0, w: 2, h: 2 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 2, h: 2 },
            sourceSize: { w: 2, h: 2 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/background.tif": {
            frame: { x: 3, y: 0, w: 2, h: 2 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 2, h: 2 },
            sourceSize: { w: 2, h: 2 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/E.gif": {
            frame: { x: 87, y: 120, w: 67, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 67, h: 72 },
            sourceSize: { w: 67, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/E.tif": {
            frame: { x: 154, y: 120, w: 67, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 67, h: 72 },
            sourceSize: { w: 67, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/G.gif": {
            frame: { x: 221, y: 120, w: 72, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 72, h: 72 },
            sourceSize: { w: 72, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/G.tif": {
            frame: { x: 293, y: 120, w: 72, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 72, h: 72 },
            sourceSize: { w: 72, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/I.gif": {
            frame: { x: 365, y: 120, w: 30, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 30, h: 72 },
            sourceSize: { w: 30, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/I.tif": {
            frame: { x: 395, y: 120, w: 30, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 30, h: 72 },
            sourceSize: { w: 30, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/L.gif": {
            frame: { x: 425, y: 120, w: 63, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 63, h: 72 },
            sourceSize: { w: 63, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/L.tif": {
            frame: { x: 488, y: 120, w: 63, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 63, h: 72 },
            sourceSize: { w: 63, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/M.gif": {
            frame: { x: 551, y: 120, w: 91, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 91, h: 72 },
            sourceSize: { w: 91, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/M.tif": {
            frame: { x: 642, y: 120, w: 91, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 91, h: 72 },
            sourceSize: { w: 91, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/N.gif": {
            frame: { x: 733, y: 120, w: 82, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 82, h: 72 },
            sourceSize: { w: 82, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/N.tif": {
            frame: { x: 815, y: 120, w: 82, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 82, h: 72 },
            sourceSize: { w: 82, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/R.gif": {
            frame: { x: 897, y: 120, w: 81, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 81, h: 72 },
            sourceSize: { w: 81, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/R.tif": {
            frame: { x: 978, y: 120, w: 81, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 81, h: 72 },
            sourceSize: { w: 81, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/S.gif": {
            frame: { x: 1059, y: 120, w: 68, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 68, h: 72 },
            sourceSize: { w: 68, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/S.tif": {
            frame: { x: 1127, y: 120, w: 68, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 68, h: 72 },
            sourceSize: { w: 68, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/V.gif": {
            frame: { x: 1195, y: 120, w: 87, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 87, h: 72 },
            sourceSize: { w: 87, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "output/V.tif": {
            frame: { x: 1282, y: 120, w: 87, h: 72 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 87, h: 72 },
            sourceSize: { w: 87, h: 72 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "pM_berlin.tif": {
            frame: { x: 2555, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "pM_berlin_on.tif": {
            frame: { x: 2587, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "pM_berlinTest.tif": {
            frame: { x: 2571, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "pM_gmg.tif": {
            frame: { x: 2603, y: 0, w: 53, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 53, h: 16 },
            sourceSize: { w: 53, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "pM_gmg_on.tif": {
            frame: { x: 2656, y: 0, w: 53, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 53, h: 16 },
            sourceSize: { w: 53, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "pM_medikit.tif": {
            frame: { x: 2709, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "pM_medikit_on.tif": {
            frame: { x: 2725, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "potion digits/digits.tif": {
            frame: { x: 2741, y: 0, w: 73, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 73, h: 16 },
            sourceSize: { w: 73, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "potion digits/tif/digit01.tif": {
            frame: { x: 21, y: 0, w: 6, h: 8 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 6, h: 8 },
            sourceSize: { w: 6, h: 8 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "potion digits/tif/digit02.tif": {
            frame: { x: 27, y: 0, w: 6, h: 8 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 6, h: 8 },
            sourceSize: { w: 6, h: 8 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "potion digits/tif/digit03.tif": {
            frame: { x: 33, y: 0, w: 6, h: 8 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 6, h: 8 },
            sourceSize: { w: 6, h: 8 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "potion digits/tif/digit04.tif": {
            frame: { x: 39, y: 0, w: 6, h: 8 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 6, h: 8 },
            sourceSize: { w: 6, h: 8 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "potion digits/tif/digit05.tif": {
            frame: { x: 45, y: 0, w: 6, h: 8 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 6, h: 8 },
            sourceSize: { w: 6, h: 8 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "potion digits/tif/digit06.tif": {
            frame: { x: 51, y: 0, w: 6, h: 8 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 6, h: 8 },
            sourceSize: { w: 6, h: 8 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "potion digits/tif/digit07.tif": {
            frame: { x: 57, y: 0, w: 6, h: 8 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 6, h: 8 },
            sourceSize: { w: 6, h: 8 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "potion digits/tif/digit08.tif": {
            frame: { x: 63, y: 0, w: 6, h: 8 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 6, h: 8 },
            sourceSize: { w: 6, h: 8 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "potion digits/tif/digit09.tif": {
            frame: { x: 69, y: 0, w: 6, h: 8 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 6, h: 8 },
            sourceSize: { w: 6, h: 8 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "potion digits/tif/digit10.tif": {
            frame: { x: 75, y: 0, w: 6, h: 8 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 6, h: 8 },
            sourceSize: { w: 6, h: 8 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "sc_sign.tif": {
            frame: { x: 29, y: 48, w: 84, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 84, h: 28 },
            sourceSize: { w: 84, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "score_bw.tif": {
            frame: { x: 1021, y: 0, w: 64, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 64, h: 13 },
            sourceSize: { w: 64, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "score_grey.tif": {
            frame: { x: 1085, y: 0, w: 64, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 64, h: 13 },
            sourceSize: { w: 64, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scoredigits/tif/digit00.tif": {
            frame: { x: 1149, y: 0, w: 12, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 12, h: 13 },
            sourceSize: { w: 12, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scoredigits/tif/digit01.tif": {
            frame: { x: 1161, y: 0, w: 12, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 12, h: 13 },
            sourceSize: { w: 12, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scoredigits/tif/digit02.tif": {
            frame: { x: 1173, y: 0, w: 12, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 12, h: 13 },
            sourceSize: { w: 12, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scoredigits/tif/digit03.tif": {
            frame: { x: 1185, y: 0, w: 12, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 12, h: 13 },
            sourceSize: { w: 12, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scoredigits/tif/digit04.tif": {
            frame: { x: 1197, y: 0, w: 12, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 12, h: 13 },
            sourceSize: { w: 12, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scoredigits/tif/digit05.tif": {
            frame: { x: 1209, y: 0, w: 12, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 12, h: 13 },
            sourceSize: { w: 12, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scoredigits/tif/digit06.tif": {
            frame: { x: 1221, y: 0, w: 12, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 12, h: 13 },
            sourceSize: { w: 12, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scoredigits/tif/digit07.tif": {
            frame: { x: 1233, y: 0, w: 12, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 12, h: 13 },
            sourceSize: { w: 12, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scoredigits/tif/digit08.tif": {
            frame: { x: 1245, y: 0, w: 12, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 12, h: 13 },
            sourceSize: { w: 12, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scoredigits/tif/digit09.tif": {
            frame: { x: 1257, y: 0, w: 12, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 12, h: 13 },
            sourceSize: { w: 12, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scorefont_bw.tif": {
            frame: { x: 1269, y: 0, w: 129, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 129, h: 13 },
            sourceSize: { w: 129, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scorefont_colour.tif": {
            frame: { x: 1398, y: 0, w: 129, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 129, h: 13 },
            sourceSize: { w: 129, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scorefont_grey.tif": {
            frame: { x: 1527, y: 0, w: 129, h: 13 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 129, h: 13 },
            sourceSize: { w: 129, h: 13 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scroll_blue.tif": {
            frame: { x: 3342, y: 0, w: 18, h: 18 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 18, h: 18 },
            sourceSize: { w: 18, h: 18 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scroll_grey_hi.tif": {
            frame: { x: 3360, y: 0, w: 18, h: 18 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 18, h: 18 },
            sourceSize: { w: 18, h: 18 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scroll_orange.tif": {
            frame: { x: 3378, y: 0, w: 18, h: 18 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 18, h: 18 },
            sourceSize: { w: 18, h: 18 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scroll_purple.tif": {
            frame: { x: 3396, y: 0, w: 18, h: 18 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 18, h: 18 },
            sourceSize: { w: 18, h: 18 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scroll_white.tif": {
            frame: { x: 3414, y: 0, w: 18, h: 18 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 18, h: 18 },
            sourceSize: { w: 18, h: 18 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scroll_yellow.tif": {
            frame: { x: 3432, y: 0, w: 18, h: 18 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 18, h: 18 },
            sourceSize: { w: 18, h: 18 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scrollerMask.tif": {
            frame: { x: 1905, y: 20, w: 619, h: 26 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 619, h: 26 },
            sourceSize: { w: 619, h: 26 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "scrollerMaskAlpha.tif": {
            frame: { x: 2524, y: 20, w: 619, h: 26 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 619, h: 26 },
            sourceSize: { w: 619, h: 26 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "SCSI0001.tif": {
            frame: { x: 3143, y: 20, w: 84, h: 28 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 84, h: 28 },
            sourceSize: { w: 84, h: 28 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "selectbox_hi.tif": {
            frame: { x: 2814, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "soundoff.tif": {
            frame: { x: 352, y: 48, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "soundon.tif": {
            frame: { x: 384, y: 48, w: 32, h: 32 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
            sourceSize: { w: 32, h: 32 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "source/bw.tif": {
            frame: { x: 1648, y: 120, w: 1888, h: 136 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 1888, h: 136 },
            sourceSize: { w: 1888, h: 136 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "source/outline.tif": {
            frame: { x: 0, y: 256, w: 3200, h: 136 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 3200, h: 136 },
            sourceSize: { w: 3200, h: 136 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "start_butt.gif": {
            frame: { x: 936, y: 20, w: 104, h: 24 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 104, h: 24 },
            sourceSize: { w: 104, h: 24 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "tr_forg.tif": {
            frame: { x: 2742, y: 48, w: 32, h: 50 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 32, h: 50 },
            sourceSize: { w: 32, h: 50 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "tv.tif": {
            frame: { x: 1090, y: 20, w: 20, h: 25 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 20, h: 25 },
            sourceSize: { w: 20, h: 25 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "tv2.tif": {
            frame: { x: 1110, y: 20, w: 20, h: 25 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 20, h: 25 },
            sourceSize: { w: 20, h: 25 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wA.tif": {
            frame: { x: 2830, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wAwlk01.tif": {
            frame: { x: 2846, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wAwlk02.tif": {
            frame: { x: 2862, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wAwlk03.tif": {
            frame: { x: 2878, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wAwlk04.tif": {
            frame: { x: 2894, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wAwlk05.tif": {
            frame: { x: 2910, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wAwlk06.tif": {
            frame: { x: 2926, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wAwlk07.tif": {
            frame: { x: 2942, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wAwlk08.tif": {
            frame: { x: 2958, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wBeard.tif": {
            frame: { x: 401, y: 0, w: 6, h: 11 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 6, h: 11 },
            sourceSize: { w: 6, h: 11 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wbFlaetorlin.tif": {
            frame: { x: 1130, y: 20, w: 25, h: 25 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 25, h: 25 },
            sourceSize: { w: 25, h: 25 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wbFoelin.tif": {
            frame: { x: 1155, y: 20, w: 25, h: 25 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 25, h: 25 },
            sourceSize: { w: 25, h: 25 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wBlank.tif": {
            frame: { x: 2974, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wbMerlin.tif": {
            frame: { x: 1180, y: 20, w: 25, h: 25 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 25, h: 25 },
            sourceSize: { w: 25, h: 25 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wbMortillin.tif": {
            frame: { x: 1205, y: 20, w: 25, h: 25 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 25, h: 25 },
            sourceSize: { w: 25, h: 25 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wFl.tif": {
            frame: { x: 2990, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wFo.tif": {
            frame: { x: 3006, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wG.tif": {
            frame: { x: 3022, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wM_eBeam.tif": {
            frame: { x: 3038, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wM_eBeam_on.tif": {
            frame: { x: 3054, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wM_eBlast.tif": {
            frame: { x: 3070, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wM_eBlast_on.tif": {
            frame: { x: 3086, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wM_monsterSummon.tif": {
            frame: { x: 3102, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wM_monsterSummon_on.tif": {
            frame: { x: 3118, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wM_morph.tif": {
            frame: { x: 3134, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wM_morph_on.tif": {
            frame: { x: 3150, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wP.tif": {
            frame: { x: 3166, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wPwlk01.tif": {
            frame: { x: 3182, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wPwlk02.tif": {
            frame: { x: 3198, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wPwlk03.tif": {
            frame: { x: 3214, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wPwlk04.tif": {
            frame: { x: 3230, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wPwlk05.tif": {
            frame: { x: 3246, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wPwlk06.tif": {
            frame: { x: 3262, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wPwlk07.tif": {
            frame: { x: 3278, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wPwlk08.tif": {
            frame: { x: 3294, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wr_eBeam.tif": {
            frame: { x: 1756, y: 0, w: 78, h: 15 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 78, h: 15 },
            sourceSize: { w: 78, h: 15 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wr_eBlast.tif": {
            frame: { x: 1834, y: 0, w: 75, h: 15 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 75, h: 15 },
            sourceSize: { w: 75, h: 15 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wr_gameSaved.tif": {
            frame: { x: 407, y: 0, w: 76, h: 12 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 76, h: 12 },
            sourceSize: { w: 76, h: 12 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wr_monsterSummon.tif": {
            frame: { x: 483, y: 0, w: 102, h: 12 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 102, h: 12 },
            sourceSize: { w: 102, h: 12 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wr_morph.tif": {
            frame: { x: 1909, y: 0, w: 37, h: 15 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 37, h: 15 },
            sourceSize: { w: 37, h: 15 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "writingMod/col.tif": {
            frame: { x: 3473, y: 0, w: 2, h: 20 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 2, h: 20 },
            sourceSize: { w: 2, h: 20 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "writingMod/mask.tif": {
            frame: { x: 3475, y: 0, w: 2, h: 20 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 2, h: 20 },
            sourceSize: { w: 2, h: 20 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wU.tif": {
            frame: { x: 3310, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
        "wV.tif": {
            frame: { x: 3326, y: 0, w: 16, h: 16 },
            rotated: false,
            trimmed: false,
            spriteSourceSize: { x: 0, y: 0, w: 16, h: 16 },
            sourceSize: { w: 16, h: 16 },
            anchor: { x: 0.5, y: 0.5 },
        },
    },
    animations: {
        CH: ["CH0001.tif", "CH0002.tif", "CH0003.tif", "CH0004.tif"],
        backgroundAlpha: [
            "backgroundAlpha01.tif",
            "backgroundAlpha02.tif",
            "backgroundAlpha03.tif",
        ],
        "charge/wAchrg": [
            "charge/wAchrg01.tif",
            "charge/wAchrg02.tif",
            "charge/wAchrg03.tif",
            "charge/wAchrg04.tif",
        ],
        "charge/wFlchrg": [
            "charge/wFlchrg01.tif",
            "charge/wFlchrg02.tif",
            "charge/wFlchrg03.tif",
            "charge/wFlchrg04.tif",
        ],
        "charge/wFochrg": [
            "charge/wFochrg01.tif",
            "charge/wFochrg02.tif",
            "charge/wFochrg03.tif",
            "charge/wFochrg04.tif",
        ],
        "charge/wGchrg": [
            "charge/wGchrg01.tif",
            "charge/wGchrg02.tif",
            "charge/wGchrg03.tif",
            "charge/wGchrg04.tif",
        ],
        "charge/wPchrg": [
            "charge/wPchrg01.tif",
            "charge/wPchrg02.tif",
            "charge/wPchrg03.tif",
            "charge/wPchrg04.tif",
        ],
        "charge/wUchrg": [
            "charge/wUchrg01.tif",
            "charge/wUchrg02.tif",
            "charge/wUchrg03.tif",
            "charge/wUchrg04.tif",
        ],
        "charge/wVchrg": [
            "charge/wVchrg01.tif",
            "charge/wVchrg02.tif",
            "charge/wVchrg03.tif",
            "charge/wVchrg04.tif",
        ],
        "potion digits/tif/digit": [
            "potion digits/tif/digit01.tif",
            "potion digits/tif/digit02.tif",
            "potion digits/tif/digit03.tif",
            "potion digits/tif/digit04.tif",
            "potion digits/tif/digit05.tif",
            "potion digits/tif/digit06.tif",
            "potion digits/tif/digit07.tif",
            "potion digits/tif/digit08.tif",
            "potion digits/tif/digit09.tif",
            "potion digits/tif/digit10.tif",
        ],
        "scoredigits/tif/digit": [
            "scoredigits/tif/digit00.tif",
            "scoredigits/tif/digit01.tif",
            "scoredigits/tif/digit02.tif",
            "scoredigits/tif/digit03.tif",
            "scoredigits/tif/digit04.tif",
            "scoredigits/tif/digit05.tif",
            "scoredigits/tif/digit06.tif",
            "scoredigits/tif/digit07.tif",
            "scoredigits/tif/digit08.tif",
            "scoredigits/tif/digit09.tif",
        ],
        wAwlk: [
            "wAwlk01.tif",
            "wAwlk02.tif",
            "wAwlk03.tif",
            "wAwlk04.tif",
            "wAwlk05.tif",
            "wAwlk06.tif",
            "wAwlk07.tif",
            "wAwlk08.tif",
        ],
        wPwlk: [
            "wPwlk01.tif",
            "wPwlk02.tif",
            "wPwlk03.tif",
            "wPwlk04.tif",
            "wPwlk05.tif",
            "wPwlk06.tif",
            "wPwlk07.tif",
            "wPwlk08.tif",
        ],
    },
    meta: {
        app: "https://www.codeandweb.com/texturepacker",
        version: "1.0",
        image: "ui.png",
        format: "RGBA8888",
        size: { w: 3575, h: 392 },
        scale: "1",
        smartupdate:
            "$TexturePacker:SmartUpdate:4fb89baffdbf679a53300713f7a1ea19:850a41b0c1823f2069f9c76bc9ba0762:5b04aa198265472a3c5f56958d78e97b$",
    },
};
